# Generated by Django 5.2.3 on 2025-08-01 11:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking Inquiry', 'verbose_name_plural': 'Booking Inquiries'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use', null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='booking_id',
            field=models.CharField(default='JTT17540482684769', help_text='Unique booking identifier', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='datetime',
            field=models.DateTimeField(help_text='Pickup date and time'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='destination',
            field=models.CharField(help_text='Drop-off location', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='origin',
            field=models.CharField(help_text='Pickup location', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='return_datetime',
            field=models.DateTimeField(blank=True, help_text='Return date and time (for round trips)', null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='trip_type',
            field=models.CharField(choices=[('one-way', 'One Way'), ('round-trip', 'Round Trip'), ('city', 'City Roaming')], default='one-way', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('changed_by', models.CharField(default='System', max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='booking.inquiry')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='booking.inquiry')),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedback',
            },
        ),
    ]
