# Generated by Django 5.2.3 on 2025-08-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_inquiry_options_inquiry_admin_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerFeedback',
        ),
    ]
