# Generated by Django 5.2.3 on 2025-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_car_created_at_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularroute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='route_images/'),
        ),
    ]
