# Generated by Django 5.2.3 on 2025-08-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_popularroute_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularroute',
            name='distance_km',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='popularroute',
            name='rate',
            field=models.CharField(max_length=100),
        ),
    ]
