# Generated by Django 5.2.3 on 2025-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_convert_images_to_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
