# Generated by Django 5.2.3 on 2025-08-10 12:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_cartype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='maximum_rate_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum rate per km for price range calculation', max_digits=6),
        ),
        migrations.AddField(
            model_name='cartype',
            name='minimum_rate_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum rate per km for price range calculation', max_digits=6),
        ),
    ]
