# Generated by Django 5.2.3 on 2025-08-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_cartype_maximum_rate_per_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the gallery image', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description for the image', null=True)),
                ('image_data', models.BinaryField(help_text='Binary image data')),
                ('image_filename', models.CharField(help_text='Original filename', max_length=255)),
                ('image_content_type', models.CharField(help_text='Image MIME type', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which images appear (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is visible in the gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
