# Generated by Django 5.2.3 on 2025-08-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driver_contact',
        ),
        migrations.RemoveField(
            model_name='car',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='registration_number',
        ),
    ]
