# Generated by Django 5.2.3 on 2025-08-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_car_driver_contact_remove_car_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('all', 'All Images'), ('destinations', 'Destinations'), ('fleet', 'Our Fleet'), ('journeys', 'Journeys')], default='all', max_length=50),
        ),
    ]
