# Generated by Django 5.2.3 on 2025-08-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_gallery_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
    ]
