# Generated by Django 5.2.3 on 2025-08-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_remove_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video_content_type',
            field=models.CharField(blank=True, help_text='Video MIME type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_data',
            field=models.BinaryField(blank=True, help_text='Binary video data', null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_filename',
            field=models.CharField(blank=True, help_text='Original video filename', max_length=255, null=True),
        ),
    ]
