# Generated by Django 5.2.3 on 2025-08-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_gallery_video_content_type_gallery_video_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_data',
            field=models.BinaryField(blank=True, help_text='Binary image data', null=True),
        ),
    ]
