# Generated by Django 5.2.3 on 2025-08-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_gallery_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_content_type',
            field=models.CharField(blank=True, help_text='Image MIME type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_filename',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
    ]
